import { BestProduct, ProductDetail } from './type';

export const MOCK_PRODUCTS: BestProduct[] = [
  {
    id: 1,
    productName: 'PC Gaming Hoàng Hà - Intel Core i9 14900K',
    productImage: 'https://hoanghapc.vn/media/product/250_5101_pc_3301_tan_cooler_master_620s.jpg',
    price: 45000000,
    sold: 120,
    sale: 10,
    description: 'Cấu hình cực khủng cho game thủ chuyên nghiệp.',
    rating: 5,
    category: {
      gender: 'Unisex',
      brand: 'Hoàng Hà',
      category: 'PC Gaming',
    },
    items: [],
    createAt: null,
    updateAt: null,
  },
  {
    id: 2,
    productName: 'Card Màn Hình ASUS ROG Strix RTX 4090',
    productImage: 'https://hoanghapc.vn/media/product/250_4521_hhpc_black_sky_4080_galax_ha1.jpg',
    price: 55000000,
    sold: 50,
    sale: 5,
    description: 'Sức mạnh đồ họa đỉnh cao.',
    rating: 5,
    category: {
      gender: 'Unisex',
      brand: 'ASUS',
      category: 'VGA',
    },
    items: [],
    createAt: null,
    updateAt: null,
  },
  {
    id: 3,
    productName: 'Màn Hình Samsung Odyssey G9 49 inch',
    productImage: 'https://hoanghapc.vn/media/product/250_5026_talos_e3_mesh_elite_black_ha8.jpg',
    price: 35000000,
    sold: 30,
    sale: 15,
    description: 'Màn hình cong siêu rộng, trải nghiệm đắm chìm.',
    rating: 4.8,
    category: {
      gender: 'Unisex',
      brand: 'Samsung',
      category: 'Monitor',
    },
    items: [],
    createAt: null,
    updateAt: null,
  },
  {
    id: 4,
    productName: 'Bàn Phím Cơ Razer BlackWidow V4 Pro',
    productImage: 'https://hoanghapc.vn/media/product/250_3208_pc_gaming_sama_3301_hyper_212_ha2.jpg',
    price: 5000000,
    sold: 200,
    sale: 0,
    description: 'Switch cơ học bền bỉ, LED RGB rực rỡ.',
    rating: 4.7,
    category: {
      gender: 'Unisex',
      brand: 'Razer',
      category: 'Keyboard',
    },
    items: [],
    createAt: null,
    updateAt: null,
  },
];

export const MOCK_PRODUCT_DETAIL: ProductDetail = {
  id: 1,
  productName: 'PC Gaming Hoàng Hà - Intel Core i9 14900K',
  productImage: 'https://hoanghapc.vn/media/product/250_5101_pc_3301_tan_cooler_master_620s.jpg',
  price: 45000000,
  sale: 10,
  sold: 120,
  description: 'Cấu hình chi tiết:\n- CPU: Intel Core i9 14900K\n- RAM: 64GB DDR5\n- VGA: RTX 4090\n- SSD: 2TB NVMe Gen5',
  rating: 5,
  categories: [
    { id: 1, name: 'Hoàng Hà', type: 'brand' },
    { id: 2, name: 'PC Gaming', type: 'category' },
  ],
  items: [
    {
      id: 101,
      size: 'Standard',
      color: 'Black',
      productImage: 'https://hoanghapc.vn/media/product/250_5101_pc_3301_tan_cooler_master_620s.jpg',
      bonusPrice: 0,
      quantity: 10,
    },
  ],
  createAt: null,
  updateAt: null,
};
